import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Test from "@/components/Test";

// app/layout.tsx
import { Outfit } from 'next/font/google';
import DeveloperBar from "@/components/DeveloperBar";

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap', // Prevents invisible text during load
  variable: '--font-outfit', // Optional: for Tailwind CSS integration
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
          className='min-w-[575px] overflow-x-auto'>
      <body
        className={`${outfit.className} antialiased `}
      >
        <DeveloperBar />
        <Header />
        {/* <Test /> */}
        {children}
      </body>
    </html>
  );
}
